import { colors } from "../../theme/tokens";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    page: {
        flex: 1,
        backgroundColor: colors.background,
        paddingTop: 42,
        paddingBottom: 98,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 14,
        gap: 12,
    },
    headerStacked: {
        alignItems: "flex-start",
        flexDirection: "column",
    },
    headerTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    title: {
        fontSize: 24,
        lineHeight: 30,
        fontWeight: "800",
        color: colors.text,
    },
    subtitle: {
        color: colors.textMuted,
        marginTop: 6,
        marginBottom: 14,
        lineHeight: 22,
    },
    headerActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flexShrink: 1,
        flexWrap: "wrap",
        justifyContent: "flex-end",
    },
    headerActionsStacked: {
        width: "100%",
        justifyContent: "flex-start",
    },
    scanButton: {
        backgroundColor: colors.primary,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 10,
    },
    scanText: {
        color: colors.surface,
        fontWeight: "700",
    },
    scanHeroCard: {
        backgroundColor: "#eef5ff",
        borderRadius: 14,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
        marginBottom: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    scanHeroTextWrap: {
        flex: 1,
    },
    scanHeroTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: "800",
    },
    scanHeroSubtitle: {
        color: colors.textMuted,
        marginTop: 6,
        lineHeight: 20,
    },
    scanHeroButton: {
        backgroundColor: colors.primary,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    scanHeroButtonText: {
        color: colors.surface,
        fontWeight: "800",
        fontSize: 13,
    },
    createBox: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 16,
        marginBottom: 10,
    },
    categoryBox: {
        backgroundColor: "#f7fbff",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 16,
        marginBottom: 10,
    },
    listStatusCard: {
        backgroundColor: colors.surface,
        borderRadius: 10,
        padding: 12,
    },
    listSectionCard: {
        backgroundColor: colors.surface,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
        marginBottom: 12,
        overflow: "hidden",
    },
    listSectionDivider: {
        marginTop: 2,
        borderBottomWidth: 1,
        borderBottomColor: colors.track,
    },
    filterChipRow: {
        flexDirection: "row",
        gap: 8,
        marginBottom: 12,
        flexWrap: "wrap",
    },
    filterChipRowCompact: {
        flexDirection: "row",
        gap: 8,
        flexWrap: "wrap",
        marginBottom: 8,
    },
    filterGroupLabel: {
        color: "#6a8098",
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
        marginBottom: 6,
    },
    filterChip: {
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    filterChipActive: {
        backgroundColor: colors.primarySoft,
        borderColor: colors.primary,
    },
    filterChipText: {
        color: "#35506d",
        fontWeight: "700",
        fontSize: 13,
    },
    filterChipTextActive: {
        color: colors.primary,
    },
    createTitle: {
        fontWeight: "700",
        color: colors.text,
        marginBottom: 12,
        lineHeight: 28,
        fontSize: 15,
    },
    categoryHelpText: {
        color: colors.textMuted,
        marginBottom: 12,
        fontSize: 13,
        lineHeight: 19,
    },
    manageCategoryButton: {
        alignSelf: "flex-start",
        backgroundColor: colors.primary,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    manageCategoryButtonText: {
        color: colors.surface,
        fontWeight: "700",
        fontSize: 13,
    },
    input: {
        borderWidth: 1,
        borderColor: "#d4dde7",
        borderRadius: 10,
        backgroundColor: colors.surface,
        color: "#1a3047",
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 14,
    },
    sectionSwitchWrap: {
        flexDirection: "row",
        gap: 8,
        marginBottom: 12,
    },
    sectionSwitchButton: {
        flex: 1,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        borderRadius: 10,
        paddingVertical: 10,
        alignItems: "center",
    },
    sectionSwitchButtonActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    sectionSwitchText: {
        color: "#35506d",
        fontWeight: "700",
        fontSize: 13,
    },
    sectionSwitchTextActive: {
        color: colors.surface,
    },
    inputError: {
        borderColor: "#d54646",
    },
    fieldError: {
        marginTop: -4,
        marginBottom: 12,
        color: "#bd1e1e",
        fontSize: 13,
        lineHeight: 18,
    },
    categoryLabel: {
        color: "#35506d",
        fontWeight: "700",
        marginBottom: 10,
    },
    categoryChipRow: {
        gap: 8,
        paddingBottom: 8,
    },
    categoryChip: {
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        borderRadius: 8,
        paddingHorizontal: 11,
        paddingVertical: 6,
    },
    categoryChipActive: {
        backgroundColor: colors.primarySoft,
        borderColor: colors.primary,
    },
    categoryChipText: {
        color: "#35506d",
        fontWeight: "700",
        fontSize: 13,
    },
    categoryChipTextActive: {
        color: colors.primary,
    },
    primaryButton: {
        backgroundColor: colors.primary,
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: "center",
        marginTop: 4,
    },
    primaryText: {
        color: colors.surface,
        fontWeight: "700",
    },
    tokenBox: {
        marginTop: 10,
        borderRadius: 10,
        padding: 10,
        backgroundColor: "#fff6de",
        borderWidth: 1,
        borderColor: "#f1d17b",
    },
    tokenLabel: {
        color: "#5a4212",
        fontWeight: "600",
        marginBottom: 4,
    },
    tokenValue: {
        color: "#6f510a",
        fontFamily: "monospace",
        fontSize: 13,
    },
    copyTokenButton: {
        marginTop: 10,
        backgroundColor: "#f7e7b5",
        borderRadius: 8,
        paddingVertical: 8,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e9cb6b",
    },
    copyTokenButtonText: {
        color: "#5a4212",
        fontWeight: "700",
        fontSize: 13,
    },
    showTokenButton: {
        marginTop: 12,
        backgroundColor: colors.primarySoft,
        borderWidth: 1,
        borderColor: "#c8daf9",
        borderRadius: 8,
        paddingVertical: 9,
        alignItems: "center",
    },
    showTokenButtonText: {
        color: colors.primary,
        fontWeight: "700",
        fontSize: 13,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(13,23,36,0.35)",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
    },
    modalCard: {
        width: "100%",
        maxWidth: 420,
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
    },
    modalTitle: {
        color: "#1a3047",
        fontWeight: "700",
        fontSize: 18,
    },
    modalSubtitle: {
        color: colors.textMuted,
        marginTop: 4,
        marginBottom: 10,
    },
    modalActions: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "flex-end",
        gap: 8,
        marginTop: 10,
    },
    provisionTokenButton: {
        backgroundColor: colors.primary,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    provisionTokenButtonText: {
        color: colors.surface,
        fontWeight: "700",
        fontSize: 13,
    },
    closeDialogButton: {
        backgroundColor: colors.primarySoft,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    closeDialogButtonText: {
        color: colors.primary,
        fontWeight: "700",
        fontSize: 13,
    },
    list: {
        flex: 1,
    },
    listContent: {
        paddingHorizontal: 16,
        paddingBottom: 160,
    },
    listHeaderManageOnly: {
        marginBottom: 0,
    },
    listSkeletonWrap: {
        gap: 8,
        marginTop: 4,
    },
    hiddenListSpacer: {
        height: 0,
    },
    card: {
        backgroundColor: colors.surface,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 0,
    },
    cardEmbedded: {
        marginBottom: 0,
        borderWidth: 0,
        borderRadius: 0,
    },
    cardEmbeddedWithDivider: {
        borderBottomWidth: 1,
        borderBottomColor: colors.track,
    },
    deviceRowCompact: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 10,
    },
    deviceRowLeft: {
        flex: 1,
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    deviceTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    deviceName: {
        fontSize: 14,
        fontWeight: "700",
        color: colors.text,
    },
    deviceCodePill: {
        marginTop: 4,
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "500",
    },
    deviceMetaInline: {
        marginTop: 2,
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "500",
    },
    deviceRowRight: {
        alignItems: "flex-end",
        justifyContent: "center",
        gap: 8,
    },
    statusTextCompact: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0.3,
    },
    statusTextOnline: {
        color: "#0a6f2f",
    },
    statusTextOffline: {
        color: "#a61d1d",
    },
    statusDot: {
        width: 10,
        height: 10,
        borderRadius: 99,
        marginTop: 2,
    },
    statusOnline: {
        backgroundColor: "#0a6f2f",
    },
    statusOffline: {
        backgroundColor: "#a61d1d",
    },
    metaCompactList: {
        gap: 2,
        marginTop: 2,
    },
    metaCompactRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    metaCompactLabel: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "500",
    },
    metaCompactValue: {
        color: colors.text,
        fontWeight: "600",
        fontSize: 13,
        flexShrink: 1,
        textAlign: "right",
    },
    cardFooter: {
        marginTop: 8,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
    },
    cardHintText: {
        flex: 1,
        color: "#6a8098",
        fontSize: 13,
        lineHeight: 16,
    },
    deleteButton: {
        alignSelf: "flex-end",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        backgroundColor: "#fff1f1",
    },
    deleteButtonText: {
        color: "#a61d1d",
        fontSize: 13,
        fontWeight: "700",
    },
    error: {
        color: "#a61d1d",
        marginBottom: 8,
    },
    empty: {
        marginTop: 18,
        textAlign: "center",
        color: colors.textMuted,
    },
    loading: {
        marginTop: 24,
    },
});

export default styles;
