import { colors } from "../../theme/tokens";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    loadingPage: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.background,
    },
    page: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        padding: 16,
        paddingBottom: 40,
    },
    title: {
        fontSize: 28,
        fontWeight: "800",
        color: colors.text,
    },
    subtitle: {
        color: colors.textMuted,
        marginTop: 6,
        marginBottom: 14,
    },
    heroCard: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
        marginBottom: 12,
    },
    heroHeader: {
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
    },
    heroEyebrow: {
        flexGrow: 1,
        flexBasis: 120,
        color: colors.text,
        fontWeight: "800",
        fontSize: 18,
    },
    heroHeaderAction: {
        flexShrink: 1,
        minHeight: 44,
        backgroundColor: colors.primary,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    heroHeaderActionText: {
        textAlign: "center",
        color: colors.surface,
        fontSize: 13,
        fontWeight: "700",
    },
    heroValue: {
        color: colors.text,
        fontSize: 26,
        fontWeight: "900",
        marginTop: 6,
    },
    heroRangeBlock: {
        marginTop: 12,
    },
    heroStats: {
        flexDirection: "row",
        gap: 10,
        marginTop: 12,
    },
    heroStatBox: {
        flex: 1,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        padding: 10,
    },
    heroStatLabel: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    heroStatValue: {
        color: colors.text,
        fontWeight: "800",
        fontSize: 18,
        marginTop: 6,
    },
    error: {
        color: "#a61d1d",
        marginBottom: 10,
    },
    success: {
        color: "#0a6f2f",
        marginBottom: 10,
    },
    card: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
        marginBottom: 12,
    },
    cardTitle: {
        color: colors.text,
        fontWeight: "800",
        marginBottom: 10,
    },
    row: {
        flexDirection: "row",
        gap: 10,
        flexWrap: "wrap",
    },
    inputGroupWide: {
        flex: 1,
        minWidth: 160,
    },
    label: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "700",
        marginBottom: 6,
    },
    input: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: colors.surfaceMuted,
        color: colors.text,
    },
    button: {
        marginTop: 12,
        backgroundColor: colors.primary,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    buttonText: {
        color: colors.surface,
        fontWeight: "800",
    },
    helperText: {
        color: colors.textMuted,
        marginTop: 8,
        lineHeight: 18,
        fontSize: 13,
    },
    presetRow: {
        flexDirection: "row",
        gap: 8,
        flexWrap: "wrap",
        marginBottom: 10,
    },
    presetButton: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: colors.surface,
    },
    presetButtonActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    presetButtonText: {
        color: "#35506d",
        fontWeight: "700",
        fontSize: 13,
    },
    presetButtonTextActive: {
        color: colors.primary,
    },
    customDateButton: {
        flex: 1,
        minWidth: 150,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: colors.surfaceMuted,
    },
    customDateLabel: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    customDateValue: {
        color: colors.text,
        fontWeight: "700",
        marginTop: 4,
    },
    rangeText: {
        color: colors.textMuted,
    },
    chipRow: {
        gap: 8,
    },
    chip: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: colors.surface,
    },
    chipActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    chipText: {
        color: "#35506d",
        fontWeight: "700",
    },
    chipTextActive: {
        color: colors.primary,
    },
    deviceRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderWidth: 1,
        borderColor: "#e4ecf8",
        borderRadius: 10,
        padding: 12,
        marginBottom: 8,
        backgroundColor: colors.surfaceMuted,
    },
    deviceRowChecked: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    checkbox: {
        width: 18,
        height: 18,
        borderRadius: 4,
        borderWidth: 1.5,
        borderColor: "#8ca1bb",
        backgroundColor: colors.surface,
    },
    checkboxChecked: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    deviceInfo: {
        flex: 1,
    },
    deviceName: {
        color: colors.text,
        fontWeight: "700",
    },
    deviceMeta: {
        color: colors.textMuted,
        marginTop: 2,
        fontSize: 13,
    },
    summaryLine: {
        color: "#27435e",
        marginBottom: 6,
        fontWeight: "600",
    },
    resultList: {
        marginTop: 10,
        gap: 8,
    },
    resultRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderTopWidth: 1,
        borderTopColor: colors.track,
        paddingTop: 10,
    },
    resultCost: {
        color: colors.primary,
        fontWeight: "800",
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(13,23,36,0.35)",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
    },
    modalCard: {
        width: "100%",
        maxWidth: 420,
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
    },
    modalTitle: {
        color: "#1a3047",
        fontWeight: "700",
        fontSize: 17,
        marginBottom: 8,
    },
    modalActions: {
        flexDirection: "row",
        justifyContent: "flex-end",
        marginTop: 10,
    },
    modalCloseButton: {
        backgroundColor: colors.primarySoft,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    modalCloseText: {
        color: colors.primary,
        fontWeight: "700",
    },
});

export default styles;
