import { colors } from "../../theme/tokens";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    loadingPage: {
        flex: 1,
        backgroundColor: colors.background,
        paddingHorizontal: 16,
        paddingTop: 36,
    },
    skeletonPage: {
        gap: 12,
    },
    skeletonKpiRow: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    page: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        paddingHorizontal: 16,
        paddingTop: 42,
        paddingBottom: 120,
    },
    header: {
        marginBottom: 0,
    },
    title: {
        fontSize: 24,
        lineHeight: 30,
        fontWeight: "800",
        color: colors.text,
        maxWidth: "88%",
    },
    subtitle: {
        marginTop: 6,
        marginBottom: 12,
        color: colors.textMuted,
        lineHeight: 22,
    },
    error: {
        color: "#a61d1d",
        marginBottom: 10,
    },
    rangeMeta: {
        color: colors.textMuted,
        marginBottom: 10,
        fontSize: 13,
    },
    presetRow: {
        flexDirection: "row",
        gap: 8,
        marginBottom: 10,
        flexWrap: "wrap",
    },
    presetButton: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingVertical: 7,
        paddingHorizontal: 12,
        backgroundColor: colors.surface,
    },
    presetButtonActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    presetText: {
        color: "#35506d",
        fontWeight: "700",
        fontSize: 13,
    },
    presetTextActive: {
        color: colors.primary,
    },
    customRangeRow: {
        flexDirection: "row",
        gap: 10,
        marginBottom: 10,
        alignItems: "stretch",
    },
    customDateButton: {
        flex: 1,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 9,
        backgroundColor: colors.surfaceMuted,
        justifyContent: "center",
    },
    customDateLabel: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    customDateValue: {
        color: colors.text,
        marginTop: 4,
        fontWeight: "600",
        fontSize: 13,
    },
    kpiRow: {
        flexDirection: "row",
        gap: 10,
        marginBottom: 10,
    },
    kpiCard: {
        flex: 1,
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
    },
    kpiWideCard: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
        marginBottom: 10,
    },
    kpiLabel: {
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    kpiValue: {
        marginTop: 6,
        color: colors.primary,
        fontSize: 22,
        fontWeight: "800",
    },
    card: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
        marginBottom: 10,
    },
    overallKpiRow: {
        flexDirection: "row",
        gap: 10,
        marginBottom: 10,
    },
    overallKpiCard: {
        flex: 1,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        padding: 10,
        backgroundColor: colors.surfaceMuted,
    },
    overallKpiValue: {
        marginTop: 6,
        color: colors.text,
        fontSize: 20,
        fontWeight: "800",
    },
    cardTitle: {
        color: colors.text,
        fontWeight: "800",
        marginBottom: 10,
        lineHeight: 28,
        fontSize: 15,
    },
    billingPreviewHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    billingPreviewLabel: {
        flex: 1,
        minWidth: 0,
        marginRight: 12,
        color: colors.textMuted,
        fontSize: 13,
        fontWeight: "700",
        textTransform: "uppercase",
    },
    billingPreviewArrow: {
        color: colors.textMuted,
        fontSize: 24,
        fontWeight: "800",
        lineHeight: 24,
    },
    billingPreviewValue: {
        marginTop: 8,
        color: colors.text,
        fontSize: 22,
        fontWeight: "900",
    },
    chartWrap: {
        gap: 8,
    },
    chartRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
        gap: 8,
    },
    chartLabel: {
        width: "100%",
        color: "#27435e",
        fontSize: 13,
    },
    chartTrack: {
        flex: 1,
        height: 10,
        borderRadius: 99,
        backgroundColor: colors.track,
        overflow: "hidden",
    },
    chartFill: {
        height: "100%",
        backgroundColor: colors.primary,
        borderRadius: 99,
    },
    chartFillCategory: {
        height: "100%",
        backgroundColor: colors.primary,
        borderRadius: 99,
    },
    chartValue: {
        minWidth: 76,
        maxWidth: "60%",
        textAlign: "right",
        color: "#27435e",
        fontWeight: "700",
        fontSize: 13,
    },
    overallChartWrap: {
        marginTop: 4,
    },
    overallBars: {
        flexDirection: "row",
        alignItems: "flex-end",
        gap: 6,
    },
    overallBarsDense: {
        flexDirection: "row",
        alignItems: "flex-end",
        gap: 6,
    },
    overallBarsScrollView: {
        width: "100%",
    },
    overallBarsScrollContent: {
        paddingBottom: 2,
        alignItems: "flex-end",
    },
    overallBarCol: {
        flex: 1,
        minWidth: 0,
        alignItems: "center",
        justifyContent: "flex-end",
    },
    overallBarColDense: {
        flexGrow: 0,
        flexShrink: 0,
        flexBasis: "auto",
    },
    overallBarTrack: {
        width: "100%",
        height: 120,
        justifyContent: "flex-end",
        backgroundColor: colors.track,
        borderRadius: 6,
        overflow: "hidden",
    },
    overallBarFill: {
        width: "100%",
        backgroundColor: colors.primary,
        borderRadius: 6,
    },
    overallBarLabel: {
        marginTop: 6,
        color: colors.textMuted,
        fontSize: 11,
        lineHeight: 16,
        textAlign: "center",
        width: "100%",
    },
    dayLineChartBox: {
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 8,
        alignItems: "center",
    },
    dayLineLabels: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 6,
    },
    dayLineLabel: {
        color: colors.textMuted,
        fontSize: 13,
    },
    filterRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginBottom: 10,
    },
    filterButton: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingVertical: 7,
        paddingHorizontal: 12,
        backgroundColor: colors.surface,
    },
    filterButtonActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    filterButtonText: {
        color: "#35506d",
        fontWeight: "700",
        fontSize: 13,
    },
    filterButtonTextActive: {
        color: colors.primary,
    },
    deviceRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: colors.track,
        borderRadius: 10,
        paddingHorizontal: 8,
        paddingVertical: 8,
        marginTop: 6,
    },
    statusDot: {
        width: 9,
        height: 9,
        borderRadius: 99,
    },
    statusOnline: {
        backgroundColor: "#0a6f2f",
    },
    statusOffline: {
        backgroundColor: "#a61d1d",
    },
    deviceInfo: {
        flex: 1,
        minWidth: 0,
    },
    deviceName: {
        color: colors.text,
        fontWeight: "700",
    },
    deviceMeta: {
        marginTop: 1,
        color: colors.textMuted,
        fontSize: 13,
    },
    deviceUsage: {
        maxWidth: "40%",
        textAlign: "right",
        color: colors.text,
        fontWeight: "700",
        fontSize: 13,
    },
    emptyText: {
        color: colors.textMuted,
        fontStyle: "italic",
    },
    hoverButtonHighlight: {
        backgroundColor: "#f3f8ff",
        borderColor: "#bfd7ff",
    },
    hoverRowHighlight: {
        backgroundColor: "#f7fbff",
        borderColor: "#d9e8ff",
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: "rgba(13,23,36,0.35)",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
    },
    modalCard: {
        width: "100%",
        maxWidth: 420,
        backgroundColor: colors.surface,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.border,
        padding: 14,
    },
    modalTitle: {
        color: "#1a3047",
        fontWeight: "700",
        fontSize: 17,
        marginBottom: 8,
    },
    modalHint: {
        color: colors.textMuted,
        fontSize: 13,
        marginTop: 8,
    },
    modalActions: {
        flexDirection: "row",
        justifyContent: "flex-end",
        marginTop: 10,
    },
    modalCloseButton: {
        backgroundColor: colors.primarySoft,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    modalCloseText: {
        color: colors.primary,
        fontWeight: "700",
    },
});

export default styles;
